version: "3"
services:
  redis:
    image: redis:latest
    restart: always
    ports:
    - "3001:6379"
    volumes:
      - C:\Users\user\Desktop\Back\docker\redis:/data
      - C:\Users\user\Desktop\Back\docker\redis\config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

