version: "3"
services:
    db:
      image: mysql:8.0.36
      restart: always
      command:
        - --lower_case_table_names=1
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=testsql
        - MYSQL_ROOT_PASSWORD=1234
        - TZ = Asia/Seoul
      volumes:
        - C:\Users\user\Desktop\Back\docker\mysql:/var/lib/mysql
