spring:
  datasource:
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backtotheearly
  jwt:
    secret: ehdgoanfrhkqorentksdlakfmrhekfaehfhr

